service: nsn-get-routing

provider:
    name: aws
    runtime: nodejs12.x
    profile: serverlessUser
    region: us-east-1
    environment:
        PORT: 3306
        DB_HOST: 'localhost'
        DB_USER: 'nsn-user'
        DB_PWD: 'password'
        DB_NAME: 'NSN-DB'
        SHORT_ENV: 'local'
        AWS_REGION: 'localhost'

plugins:
    - serverless-webpack
    - serverless-offline

package:
    individually: true

functions:
    postNsn:
        handler: postNsn
        events:
            - http:
                  path: /nsnrouting/v1/details/
                  method: post
                  cors: true
    getNsn:
        handler: getNsn
        events:
            - http:
                  path: /nsnrouting/v1/details/paginated
                  method: post
              request:
                  parameters:
                      paths:
                          id: true
    deleteNsn:
        handler: deleteNsn
        events:
            - http:
                  path: /nsnrouting/v1/details/{routingId}
                  method: DELETE
              request:
                  parameters:
                      paths:
                          id: true
    putNsn:
        handler: putNsn
        events:
            - http:
                  path: /nsnrouting/v1/details/
                  method: PUT
    test:
        handler: test
        events:
            - http:
              path: test
              method: get
