service: nsn-data

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
  environment:
    TABLE_NAME: ""

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: false
      migrate: true
    migration:
        dir: offline/migrations

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: nsn_data
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: N
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: S
        BillingMode: PAY_PER_REQUEST 
functions:
  retrieveNSNData:
    handler: getNSNData
    events:
      - http:
          path: /nsnservice/v1/details/{nsnid}
          method: GET
  test:
    handler: test
    events:
      - http:
        path: test
        method: get