pipeline {
    environment {
        APP_DIR="services/fss-ui/modules/angular/fss-ui"
        SHORT_ENV = "${env.SHORT_ENV}"
        S3_BUCKET = "fss-ui-${SHORT_ENV}.fss19-${SHORT_ENV}.fcs.gsa.gov"
    }
    agent {
        label "linux"
    }

    tools {
        nodejs "node15"
    }

    stages {
        stage('Install:awscli') {
            steps {
                sh '''
                    curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
                    unzip awscli-bundle.zip
                    ./awscli-bundle/install -b ~/aws
                '''
            }
        }
        stage('Build') {
            steps {
                git 'https://github.com/OctoConsulting/GSA_FSS19_DevOps'
                sh '''
                    npm config set prefix '~/.local/'
                    cd "${APP_DIR}"
                    npm install
                    npm run build --prod
                '''
            }
        }
        stage('Upload:s3') {
            steps {
                sh '''
                cd "${APP_DIR}"
                ~/aws s3 sync dist/fss-ui s3://${S3_BUCKET}
                '''
            }

        }
    }
}
