pipeline {
    environment {
        APP_DIR="services/cis/infrastructure/cdk/"
        SHORT_ENV = "${env.SHORT_ENV}"
        AWS_REGION = "${env.AWS_REGION}"
        AWS_ACCOUNT = "${env.AWS_ACCOUNT}"
    }
    agent {
        label "linux-admin"
    }

    tools {
        nodejs "node15"
    }

    stages {
        stage('Install') {
            steps {
                git 'https://github.com/OctoConsulting/GSA_FSS19_DevOps'
                sh '''
                    npm config set prefix '~/.local/'
                    npm install -g cdk@1.87.1
                    cd "${APP_DIR}"
                    npm install
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    cd "${APP_DIR}"
                    export SHORT_ENV="${SHORT_ENV}" AWS_ACCOUNT="${AWS_ACCOUNT}" AWS_REGION="${AWS_REGION}"
                    ~/.local/bin/cdk deploy
                '''
            }

        }
    }
}
