//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.25 at 12:17:25 PM EST 
//


package gov.gsa.fas.contractservice.contract;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PORecordsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PORecordsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PurchaseOrderNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="totalPOCost" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ContractNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BuyerCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RequisitionRecords" type="{http://contract/}RequisitionRecord" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="POLineNumber" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PORecordsType", propOrder = {
    "purchaseOrderNum",
    "totalPOCost",
    "contractNum",
    "buyerCode",
    "requisitionRecords"
})
public class PORecordsType {

    @XmlElement(name = "PurchaseOrderNum", required = true)
    protected String purchaseOrderNum;
    @XmlElement(required = true)
    protected BigDecimal totalPOCost;
    @XmlElement(name = "ContractNum", required = true)
    protected String contractNum;
    @XmlElement(name = "BuyerCode", required = true)
    protected String buyerCode;
    @XmlElement(name = "RequisitionRecords", required = true)
    protected List<RequisitionRecord> requisitionRecords;
    @XmlAttribute(name = "POLineNumber")
    protected Integer poLineNumber;

    /**
     * Gets the value of the purchaseOrderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseOrderNum() {
        return purchaseOrderNum;
    }

    /**
     * Sets the value of the purchaseOrderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseOrderNum(String value) {
        this.purchaseOrderNum = value;
    }

    /**
     * Gets the value of the totalPOCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalPOCost() {
        return totalPOCost;
    }

    /**
     * Sets the value of the totalPOCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalPOCost(BigDecimal value) {
        this.totalPOCost = value;
    }

    /**
     * Gets the value of the contractNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNum() {
        return contractNum;
    }

    /**
     * Sets the value of the contractNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNum(String value) {
        this.contractNum = value;
    }

    /**
     * Gets the value of the buyerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerCode() {
        return buyerCode;
    }

    /**
     * Sets the value of the buyerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerCode(String value) {
        this.buyerCode = value;
    }

    /**
     * Gets the value of the requisitionRecords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requisitionRecords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequisitionRecords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequisitionRecord }
     * 
     * 
     */
    public List<RequisitionRecord> getRequisitionRecords() {
        if (requisitionRecords == null) {
            requisitionRecords = new ArrayList<RequisitionRecord>();
        }
        return this.requisitionRecords;
    }

    /**
     * Gets the value of the poLineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPOLineNumber() {
        return poLineNumber;
    }

    /**
     * Sets the value of the poLineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPOLineNumber(Integer value) {
        this.poLineNumber = value;
    }

}
