//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.25 at 12:17:25 PM EST 
//


package gov.gsa.fas.contractservice.contract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ContractsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="contractRemarks" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractBeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="contractEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="efptIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ediMessageSetVersion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="formalContractNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="acoRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="acoName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="acoEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="acoPhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractorAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractNotesList" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractNotesDetails" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractorDUNS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="lineNumber" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractsType", propOrder = {
    "contractRemarks",
    "contractNumber",
    "contractBeginDate",
    "contractEndDate",
    "efptIndicator",
    "ediMessageSetVersion",
    "formalContractNumber",
    "contractType",
    "acoRegion",
    "acoName",
    "acoEmail",
    "acoPhone",
    "contractorAddress",
    "contractNotesList",
    "contractNotesDetails",
    "contractorDUNS"
})
public class ContractsType {

    @XmlElement(required = true)
    protected String contractRemarks;
    @XmlElement(required = true)
    protected String contractNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractBeginDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractEndDate;
    @XmlElement(required = true)
    protected String efptIndicator;
    @XmlElement(required = true)
    protected String ediMessageSetVersion;
    @XmlElement(required = true)
    protected String formalContractNumber;
    @XmlElement(required = true)
    protected String contractType;
    @XmlElement(required = true)
    protected String acoRegion;
    @XmlElement(required = true)
    protected String acoName;
    @XmlElement(required = true)
    protected String acoEmail;
    @XmlElement(required = true)
    protected String acoPhone;
    @XmlElement(required = true)
    protected String contractorAddress;
    @XmlElement(required = true)
    protected String contractNotesList;
    @XmlElement(required = true)
    protected String contractNotesDetails;
    @XmlElement(required = true)
    protected String contractorDUNS;
    @XmlAttribute(name = "lineNumber")
    protected Integer lineNumber;

    /**
     * Gets the value of the contractRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractRemarks() {
        return contractRemarks;
    }

    /**
     * Sets the value of the contractRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractRemarks(String value) {
        this.contractRemarks = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the contractBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractBeginDate() {
        return contractBeginDate;
    }

    /**
     * Sets the value of the contractBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractBeginDate(XMLGregorianCalendar value) {
        this.contractBeginDate = value;
    }

    /**
     * Gets the value of the contractEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractEndDate() {
        return contractEndDate;
    }

    /**
     * Sets the value of the contractEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractEndDate(XMLGregorianCalendar value) {
        this.contractEndDate = value;
    }

    /**
     * Gets the value of the efptIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEfptIndicator() {
        return efptIndicator;
    }

    /**
     * Sets the value of the efptIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEfptIndicator(String value) {
        this.efptIndicator = value;
    }

    /**
     * Gets the value of the ediMessageSetVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdiMessageSetVersion() {
        return ediMessageSetVersion;
    }

    /**
     * Sets the value of the ediMessageSetVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdiMessageSetVersion(String value) {
        this.ediMessageSetVersion = value;
    }

    /**
     * Gets the value of the formalContractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormalContractNumber() {
        return formalContractNumber;
    }

    /**
     * Sets the value of the formalContractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormalContractNumber(String value) {
        this.formalContractNumber = value;
    }

    /**
     * Gets the value of the contractType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * Sets the value of the contractType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractType(String value) {
        this.contractType = value;
    }

    /**
     * Gets the value of the acoRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcoRegion() {
        return acoRegion;
    }

    /**
     * Sets the value of the acoRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcoRegion(String value) {
        this.acoRegion = value;
    }

    /**
     * Gets the value of the acoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcoName() {
        return acoName;
    }

    /**
     * Sets the value of the acoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcoName(String value) {
        this.acoName = value;
    }

    /**
     * Gets the value of the acoEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcoEmail() {
        return acoEmail;
    }

    /**
     * Sets the value of the acoEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcoEmail(String value) {
        this.acoEmail = value;
    }

    /**
     * Gets the value of the acoPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcoPhone() {
        return acoPhone;
    }

    /**
     * Sets the value of the acoPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcoPhone(String value) {
        this.acoPhone = value;
    }

    /**
     * Gets the value of the contractorAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorAddress() {
        return contractorAddress;
    }

    /**
     * Sets the value of the contractorAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorAddress(String value) {
        this.contractorAddress = value;
    }

    /**
     * Gets the value of the contractNotesList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNotesList() {
        return contractNotesList;
    }

    /**
     * Sets the value of the contractNotesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNotesList(String value) {
        this.contractNotesList = value;
    }

    /**
     * Gets the value of the contractNotesDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNotesDetails() {
        return contractNotesDetails;
    }

    /**
     * Sets the value of the contractNotesDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNotesDetails(String value) {
        this.contractNotesDetails = value;
    }

    /**
     * Gets the value of the contractorDUNS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorDUNS() {
        return contractorDUNS;
    }

    /**
     * Sets the value of the contractorDUNS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorDUNS(String value) {
        this.contractorDUNS = value;
    }

    /**
     * Gets the value of the lineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLineNumber() {
        return lineNumber;
    }

    /**
     * Sets the value of the lineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineNumber(Integer value) {
        this.lineNumber = value;
    }

}
