//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.25 at 12:17:25 PM EST 
//


package gov.gsa.fas.contractservice.contract;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the contract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PORequest_QNAME = new QName("http://contract/", "PORequest");
    private final static QName _GetContractDataResponse_QNAME = new QName("http://contract/", "getContractDataResponse");
    private final static QName _ListContracts_QNAME = new QName("http://contract/", "listContracts");
    private final static QName _ListContractsResponse_QNAME = new QName("http://contract/", "listContractsResponse");
    private final static QName _ContractDetails_QNAME = new QName("http://contract/", "ContractDetails");
    private final static QName _ContractDetailsResponse_QNAME = new QName("http://contract/", "contractDetailsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: contract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PORequestType }
     * 
     */
    public PORequestType createPORequestType() {
        return new PORequestType();
    }

    /**
     * Create an instance of {@link GetContractDataResponse }
     * 
     */
    public GetContractDataResponse createGetContractDataResponse() {
        return new GetContractDataResponse();
    }

    /**
     * Create an instance of {@link ListContractsType }
     * 
     */
    public ListContractsType createListContractsType() {
        return new ListContractsType();
    }

    /**
     * Create an instance of {@link ContractsType }
     * 
     */
    public ContractsType createContractsType() {
        return new ContractsType();
    }

    /**
     * Create an instance of {@link Authentication }
     * 
     */
    public Authentication createAuthentication() {
        return new Authentication();
    }

    /**
     * Create an instance of {@link PORecordsType }
     * 
     */
    public PORecordsType createPORecordsType() {
        return new PORecordsType();
    }

    /**
     * Create an instance of {@link RequisitionRecord }
     * 
     */
    public RequisitionRecord createRequisitionRecord() {
        return new RequisitionRecord();
    }

    /**
     * Create an instance of {@link CSDetailPO }
     * 
     */
    public CSDetailPO createCSDetailPO() {
        return new CSDetailPO();
    }

    /**
     * Create an instance of {@link RequisitionRes }
     * 
     */
    public RequisitionRes createRequisitionRes() {
        return new RequisitionRes();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PORequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PORequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://contract/", name = "PORequest")
    public JAXBElement<PORequestType> createPORequest(PORequestType value) {
        return new JAXBElement<PORequestType>(_PORequest_QNAME, PORequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetContractDataResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetContractDataResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://contract/", name = "getContractDataResponse")
    public JAXBElement<GetContractDataResponse> createGetContractDataResponse(GetContractDataResponse value) {
        return new JAXBElement<GetContractDataResponse>(_GetContractDataResponse_QNAME, GetContractDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://contract/", name = "listContracts")
    public JAXBElement<String> createListContracts(String value) {
        return new JAXBElement<String>(_ListContracts_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListContractsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ListContractsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://contract/", name = "listContractsResponse")
    public JAXBElement<ListContractsType> createListContractsResponse(ListContractsType value) {
        return new JAXBElement<ListContractsType>(_ListContractsResponse_QNAME, ListContractsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://contract/", name = "ContractDetails")
    public JAXBElement<String> createContractDetails(String value) {
        return new JAXBElement<String>(_ContractDetails_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ContractsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://contract/", name = "contractDetailsResponse")
    public JAXBElement<ContractsType> createContractDetailsResponse(ContractsType value) {
        return new JAXBElement<ContractsType>(_ContractDetailsResponse_QNAME, ContractsType.class, null, value);
    }

}
